version: "3.9"
services:
  db:
    image: postgres:17
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: keyboardshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Root123!
    volumes:
    - dbdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
volumes:
  dbdata:
    driver: local

